### PR TITLE
Fix repo slug in YAML settings file

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description
Change repo slug

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@Naylin15 |1|

### References

Closes #N/A
Related #N/A
Depends on #N/A

### CODE REVIEW

**Review by rafaelje — APPROVED** [review]
Reviewed

**Comment by Naylin15** [comment]
Hi, @rafaelje @ajsb85 

I'm merging this PR because due to the incorrect name of the project, the tests on Circle won't even start

In fact, this branch doesn't even appear on Circle CI

captura de pantalla 2018-07-13 a la s 4 33 51 p m

**Comment by ajsb85** [comment]
Hi, @Naylin15 
We are migrating also the `gh-page` from Travis CI to CircleCI.

**Comment by Naylin15** [comment]
Ok, I'll make the migration in the repos 👍

**Pull request merged**
