### PR TITLE
Add new sample folder

### LINKED ISSUE #42: Artifacts of the Kotlin app example
Hi, @rafaelje 

We need to create a folder with both examples, Java and Kotlin.
The contributor @JMEspiz will create the entire example for Kotlin.
Based on this PR: https://github.com/flyve-mdm/flyve-mdm-android-inventory/pull/41

Then you can continue with the CI/CD to upload the artefacts to the GitHub release.

Thanks, and good luck @JMEspiz

Ref: https://github.com/flyve-mdm/flyve-mdm-android-inventory/issues/18

### PR DESCRIPTION
**Pull request by JMEspiz**
Hi @ajsb85 @rafaelje,

this PR Close #42.

### CODE REVIEW

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Review by rafaelje — DISMISSED** [review]
Reviewed looks good for me 👍

**Comment by ajsb85** [comment]
@JMEspiz @Rafaelje could you improve, review and merge this PR?

**Comment by rafaelje** [comment]
@ajsb85 Yes I can please let me test it to merge

**Comment by rafaelje** [comment]
@JMEspiz if we are going to improve this, please can you create this folder structure for the example with kotlin and java with isolated projects:

captura de pantalla 2017-10-07 a las 2 53 25 p m

**Comment by ajsb85** [comment]
Hi, @rafaelje 
For me it's ok, 

image

**Review by ajsb85 — CHANGES_REQUESTED** [review]
Change the samples folder name to examples, and fix the commit message.

**Comment by JMEspiz** [comment]
Hi @ajsb85 @rafaelje, I'm going to make the requested changes and then I'll send a new PR.

**Comment by ajsb85** [comment]
You can edit this same PR @JMEspiz

**Comment by rafaelje** [comment]
@JMEspiz Thanks! you can send your new commit to this PR too 👍

**Comment by JMEspiz** [comment]
You are right @ajsb85 @rafaelje.. I'm going to send a new commit

**Comment by rafaelje** [comment]
@JMEspiz great job!, but please remove the 'example' folder and just keep with samples

**Review by rafaelje — APPROVED** [review]
Reviewed 👍

**Pull request merged**
