### PR TITLE
Improve CI workflow & Documentation

### LINKED ISSUE #127: HTML Proofer Failures
#### Observed Results:
Html proofer found 5 failures

  captura de pantalla 2018-07-13 a la s 10 39 59 a m

#### Expected behavior:

Succesfull test

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description
Improve CI workflow and documentation

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@Naylin15|18|

### References

Closes #127
Related [#167](https://github.com/flyve-mdm/android-inventory-agent/pull/167)
Related #109 
Depends on #124 
Depends on #126

### CODE REVIEW

**Review by ajsb85 — APPROVED** [review]

**Review by ajsb85 — APPROVED** [review]

**Review by ajsb85 — APPROVED** [review]

**Comment by Naylin15** [comment]
This will be the new workflow of the library:

#### On feature branch

- run Build
- run Test Api v16

#### On develop

There is a main script which include the commit validation to avoid repeated workflows, and contain the scripts related to its process.

- Setup environment (ci_setup.sh)
- Documentation (ci_documentation.sh)
  - Create Coverage, Test reports and Code Documentation (ci_generate_documentation.sh)
  - Update headers and styles for proper display on project site

#### On master

There is one main script that includes the commit validation to avoid repeated workflows, and contains the scripts related to the process.

- Setup environment (ci_setup.sh)
- Deploy Production (ci_deploy_production.sh)
  - Update version and code, generate Changelog (ci_updateversion.sh)
  - Push new tags and update develop branch (ci_push_changes.sh)
  - Create a GitHub release (ci_github_release.sh)
  - Send to Bintray (ci_bintray.sh)

### Note:

- I'll update the variables name on Circle CI as required by the conventional-github-releaser library
   GH_EMAIL >> GITHUB_EMAIL
   GH_USER >> GITHUB_USER
   GH_TOKEN >> GITHUB_TOKEN
- I moved the validation in the scripts for deploy and documentation, so it wouldn't fail on build and throw a false error when running to prevent loops
- No commits will be made on develop branch
- The changelog will be generated and published when there's a merge on master branch

**Comment by Naylin15** [comment]
The GitHub release is not being generated properly, it only shows the ci commit for the release and not according to the angular convention as specified

captura de pantalla 2018-07-11 a la s 2 19 44 p m

Also the Changelog is having repeated commits from older versions

**Comment by ajsb85** [comment]
Hi, @Naylin15 
But it's only a case of this repo? or it's for all repos that use the tool GitHub Releaser?

**Comment by Naylin15** [comment]
Hi, @ajsb85 

I've only seen this behavior on this repo alone, when making a test merge on master branch in the other android projects, the release description was generated correctly when running the library

**Comment by Naylin15** [comment]
Fixed the issue with the release description

captura de pantalla 2018-07-12 a la s 3 20 10 p m

**Comment by Naylin15** [comment]
There is an issue with the documentation, is not being updated, as it should, I've been trying to fix it and making tests

**Comment by Naylin15** [comment]
Hi, @ajsb85 @rafaelje 

This PR is ready, the documentation is being updated as it should

Thank you

**Review by rafaelje — APPROVED** [review]
Reviewed

**Pull request merged**
