### PR TITLE
Add Example on GitHub releases

### LINKED ISSUE #19: Create release
Create releases of the library

### PR DESCRIPTION
**Pull request by rafaelje**
Add Example.zip file on GitHub releases

close: https://github.com/flyve-mdm/flyve-mdm-android-inventory/issues/19

### CODE REVIEW

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Comment by ajsb85** [comment]
This branch cannot be rebased due to conflicts

**Comment by rafaelje** [comment]
@ajsb85 you can make a squash of this PR please with this comment:

feat(example): add Flyve Inventory Example

**Review by hectorerb — COMMENTED** [review]
Fine

**Comment by ajsb85** [comment]
@rafaelje I think it's better `ci(artefacts): upload app example to the GH release`
`feat` is for new features in the java code of the library.

**Comment by rafaelje** [comment]
@ajsb85 I think you are right it's better ci(artifacts)

**Pull request merged**
