### PR TITLE
Add Kotlin example Fixes #18

### LINKED ISSUE #18: Kotlin example application
Hi, @rafaelje 

Could you create a Kotlin code example for library.

Thanks in advance.

### PR DESCRIPTION
**Pull request by MohamedHussein02**
Close: #18

### CODE REVIEW

**Comment by ajsb85** [comment]
How can I help @MohamedHussein02?

**Comment by MohamedHussein02** [comment]
I want to fix #18

**Comment by ajsb85** [comment]
@MohamedHussein02 Go ahead.
I will add the label of the Hacktoberfest.
Thanks.

**Comment by MohamedHussein02** [comment]
I think you need to approve the changes before I can merge

**Comment by ajsb85** [comment]
@MohamedHussein02 Yes, the task is partially completed, you need to copy the sources in [Java](https://git.io/vd09c) and write the example in Kotlin.

**Comment by MohamedHussein02** [comment]
@ajsb85 Sorry for the misunderstanding. Check it out now. :)

**Comment by ajsb85** [comment]
@MohamedHussein02 Mashal-lah. Thank you very much.
@Rafaelje Could you take a look?
To see how we can package and upload as artefacts on the GitHub release section.

**Comment by MohamedHussein02** [comment]
@ajsb85 You're very welcome.

**Comment by rafaelje** [comment]
Hi @MohamedHussein02 I'll check it now

**Review by rafaelje — APPROVED** [review]
For me is fine we can accept! thanks @MohamedHussein02

**Comment by MohamedHussein02** [comment]
@ajsb85 @rafaelje You're welcome guys.

**Pull request merged**
