### PR TITLE
Add IMEI information at the inventory

### LINKED ISSUE #188: IMEI information
Hi, @Ivans51 

Could you confirm if we already support this information and what we can do to get it.

Thank you.

### LINKED ISSUE #198: Inventory modems in devices
We need to inventory IMEI of mobile devices. 

While we impelment a new modem component in GLPI, we need to investigate how we can detect one or several modem devices in mobile assets.

A modem can have one or several sim cards, and some devices exists with several modems, handling each at least one simcard. Some devices can hold 4 simcards. https://en.wikipedia.org/wiki/Dual_SIM

  
#### Observed Results:

not implemented
  
#### Expected behavior:

detect modems and IMEI and feed the inventory XML or JSON. 

Note: we need first to spec the implemetnation of modems in GLPI before defining the spec of the inventory data (XML or JSON).

We may already expect something like (assuming there are 2 modems having each 2 IMEI numbers)
```xml
<MODEMS>
  <IMEI>12345678890124</IMEI>
  <IMEI>123467880912314</IMEI>
</MODEMS>
<MODEMS>
  <IMEI>12345678890124</IMEI>
  <IMEI>123467880912314</IMEI>
</MODEMS>
```

### PR DESCRIPTION
**Pull request by Ivans51**
Signed-off-by: Ivan Del Pino <idelpino@teclib.com>

### Changes description

Add the tag IMEI in XML and JSON at the inventory

```XML
<REQUEST>
  <QUERY>INVENTORY</QUERY>
  <DEVICEID>android-4e024bafab01d943-2018-10-30-10-08-35</DEVICEID>
  <CONTENT>
    ...
    <MODEMS>
        <IMEI>867530020251185</IMEI>
        <IMEI>867532120251123</IMEI>
    </MODEMS>
    <MODEMS>
        <IMEI>8675311212112313</IMEI>
        <IMEI>8675312313151213</IMEI>
    </MODEMS> 
  </CONTENT>
</REQUEST>
...
```

```JSON
{
  "request": {
    "query": "INVENTORY",
    "versionClient": "example-app-kotlin",
    "deviceId": "android-4e024bafab01d943-2018-10-30-10-09-42",
    "IMEI": "867530020251185",
    "content": {
      ...
      "modems": [
        {
          "imei": "867530020251185",
          "imei": "867532120251123"
        }
      ],
      "modems": [
        {
          "imei": "8675311212112313",
          "imei": "8675312313151213"
        }
      ]
   }
  }
}
```

### Checklist

Please check if your PR fulfills the following specifications:

- [x] Tests for the changes have been added
- [x] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|ivans51 |16|

### References

Closes: https://github.com/flyve-mdm/android-inventory-library/issues/188
Closes: https://github.com/flyve-mdm/android-inventory-library/issues/198
Related #N/A
Depends on #N/A

### CODE REVIEW

**Comment by ajsb85** [comment]
Hi, @Ivans51 
BTW, each SIM card have one IMEI. But I guest the API only support the main IMEI and not multiples.

**Review by rafaelje — APPROVED** [review]

**Comment by rafaelje** [comment]
Looks like you need to implement the instrumented test on Firebase now, the update on circle comes to the inventory library project :( take a long time for this project

> Running the Android emulator is not currently supported on CircleCI 2.0. We recommend using an external service such as Firebase Test Lab to run your emulator tests from your CircleCI job.

https://support.circleci.com/hc/en-us/articles/360000028928-Testing-with-Android-emulator-on-CircleCI-2-0

**Review by ajsb85 — APPROVED** [review]

**Comment by Ivans51** [comment]
I will investigate about this issue

image

**Comment by Ivans51** [comment]
I am working in this problem

image

**Comment by Ivans51** [comment]
I'll create an issue about CI to make test instrumentation with firebase or another alternative

**Pull request merged**
